# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory in the container
WORKDIR /app/streamlit_app

# Copy the Streamlit application and its requirements file into the container
COPY streamlit_app.py .
COPY requirements_streamlit.txt .

# Install Streamlit and other dependencies
RUN pip install --no-cache-dir -r requirements_streamlit.txt

# Expose the port that Streamlit runs on
EXPOSE 8501

# Define the command to run the Streamlit application
CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
